### ISSUE TITLE
Fix xls2xml conversion so that it passes tests

### ISSUE THREAD

**Issue by Tereza-Pytelova** [IBM/watson-assistant-workbench#214]
`devel` branch stopped passing tests - maybe due to some updates?

```
STARTING: dialog_xls2xml.py
['tests/data/xls/E_EN_T2C_authoring.xlsx']
INFO: Searching in path: tests/data/xls/E_EN_T2C_authoring.xlsx
Processing xlsx file: tests/data/xls/E_EN_T2C_authoring.xlsx
 Sheet: Tutorial
Traceback (most recent call last):
  File "scripts/dialog_xls2xml.py", line 106, in <module>
    xlsxHandler.parseXLSXIntoDataBlocks(fileOrFolder)
  File "/home/travis/build/IBM/watson-assistant-workbench/scripts/XLSXHandler.py", line 102, in parseXLSXIntoDataBlocks
    if row[columnIndex] and row[columnIndex].value and not (row[columnIndex].value.startswith('//')):
IndexError: tuple index out of range
```

FYI @tomasmacek

**Comment by Tereza-Pytelova** [comment]
It is happening with `openpyxl` version `2.6`. For now I'll freeze the `openpyxl` version on `2.5.14`

**Comment by Tereza-Pytelova** [comment]
Script should be changed to work with newest version (https://openpyxl.readthedocs.io/en/stable/changes.html), assigning this to @tomasmacek .
